version: '3.9'

services:
  api:
    #image: iarynovskyi/qsport_image:latest
    image: iarynovskyi/qsport_image:multiarch
#    build:
#      context: .
#      dockerfile: Dockerfile
    container_name: flask
    env_file:
      - .env
    ports:
      - "5001:5001"
    volumes:
      - .:/QSPORT
    working_dir: /QSPORT
    command: ["python", "api/routes/app.py"]
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - api
    restart: unless-stopped
