version: '3.9'

services:
  api:
    image: iarynovskyi/qsport_image:latest
    container_name: flask
    env_file:
      - .env
    ports:
      - "5001:5001"
    volumes:
      - .:/QSPORT
    working_dir: /QSPORT
    command: ["python", "api/routes/app.py"]
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./api/routes/localhost.pem:/etc/ssl/certs/localhost.pem:ro
      - ./api/routes/localhost-key.pem:/etc/ssl/certs/localhost-key.pem:ro

    depends_on:
      - api
    restart: unless-stopped
