"""refactore db

Revision ID: 0bb89241787f
Revises: e56018466c09
Create Date: 2024-12-10 17:47:15.426093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb89241787f'
down_revision: Union[str, None] = 'e56018466c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Country',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['Sports.sport_id'], ),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_table('League',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country'], ['Country.country_id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['Sports.sport_id'], ),
    sa.PrimaryKeyConstraint('league_id')
    )
    op.create_table('Games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('team_away_id', sa.Integer(), nullable=True),
    sa.Column('team_home_id', sa.Integer(), nullable=True),
    sa.Column('score_away_team', sa.Integer(), nullable=True),
    sa.Column('score_home_team', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['Country.country_id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['League.league_id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['Sports.sport_id'], ),
    sa.ForeignKeyConstraint(['team_away_id'], ['TeamIndex.team_index_id'], ),
    sa.ForeignKeyConstraint(['team_home_id'], ['TeamIndex.team_index_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.add_column('TeamIndex', sa.Column('sport_id', sa.Integer(), nullable=True))
    op.add_column('TeamIndex', sa.Column('name', sa.String(), nullable=True))
    op.add_column('TeamIndex', sa.Column('logo', sa.String(), nullable=True))
    op.add_column('TeamIndex', sa.Column('api_id', sa.Integer(), nullable=True))
    op.add_column('TeamIndex', sa.Column('country', sa.Integer(), nullable=True))
    op.add_column('TeamIndex', sa.Column('league', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'TeamIndex', 'Sports', ['sport_id'], ['sport_id'])
    op.create_foreign_key(None, 'TeamIndex', 'League', ['league'], ['league_id'])
    op.create_foreign_key(None, 'TeamIndex', 'Country', ['country'], ['country_id'])
    op.drop_column('TeamIndex', 'team_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TeamIndex', sa.Column('team_name', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'TeamIndex', type_='foreignkey')
    op.drop_constraint(None, 'TeamIndex', type_='foreignkey')
    op.drop_constraint(None, 'TeamIndex', type_='foreignkey')
    op.drop_column('TeamIndex', 'league')
    op.drop_column('TeamIndex', 'country')
    op.drop_column('TeamIndex', 'api_id')
    op.drop_column('TeamIndex', 'logo')
    op.drop_column('TeamIndex', 'name')
    op.drop_column('TeamIndex', 'sport_id')
    op.drop_table('Games')
    op.drop_table('League')
    op.drop_table('Country')
    # ### end Alembic commands ###
