"""add initial values to interactions

Revision ID: 0d93e8ea82b6
Revises: 47f635e8f66a
Create Date: 2025-03-07 18:17:00.515199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d93e8ea82b6'
down_revision: Union[str, None] = '47f635e8f66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        INSERT INTO "InteractionTypes" (interaction_type_id, name) VALUES
        (1, 'like'),
        (2, 'dislike'),
        (3, 'read'),
        (4, 'open'),
        (5, comment);
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('News', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('News', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("""
        DELETE FROM "InteractionTypes" WHERE interaction_type_id IN (1, 2, 3, 4, 5);
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('News', 'views')
    op.drop_column('News', 'likes')
    # ### end Alembic commands ###
