"""fixed tables

Revision ID: 0e5276064e50
Revises: 58c28aef9014
Create Date: 2025-02-02 18:37:30.229850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5276064e50'
down_revision: Union[str, None] = '58c28aef9014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Streams_Status_stream_id_fkey', 'Streams_Status', type_='foreignkey')
    op.create_foreign_key(None, 'Streams_Status', 'Streams', ['stream_id'], ['stream_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Streams_Status', type_='foreignkey')
    op.create_foreign_key('Streams_Status_stream_id_fkey', 'Streams_Status', 'Streams', ['stream_id'], ['stream_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
