"""add recommendations and views_timestamp-datetime

Revision ID: 27eb623b7b34
Revises: 0e5276064e50
Create Date: 2025-02-02 19:43:06.910897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27eb623b7b34'
down_revision: Union[str, None] = 'd64bb5d9a9e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_recommendations',
    sa.Column('user_recommendations_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['News.news_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('user_recommendations_id')
    )
    op.alter_column('Views', 'timestamp',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using='"timestamp"::timestamp without time zone')
    op.create_table('Streams_Status',
                    sa.Column('streams_status_id', sa.Integer(), nullable=False),
                    sa.Column('stream_id', sa.Integer(), nullable=True),
                    sa.Column('status_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['stream_id'], ['Streams.stream_id'], ),
                    sa.PrimaryKeyConstraint('streams_status_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Views', 'timestamp',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_table('User_recommendations')
    op.drop_table('Streams_Status')
    # ### end Alembic commands ###
