"""fix

Revision ID: 33e92569d5d5
Revises: c444f031961a
Create Date: 2024-11-18 21:14:30.653371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e92569d5d5'
down_revision: Union[str, None] = 'c444f031961a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TeamIndex',
    sa.Column('team_index_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['News.news_id'], ),
    sa.PrimaryKeyConstraint('team_index_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TeamIndex')
    # ### end Alembic commands ###
