"""delete old table ClubPreferences

Revision ID: 42e239ddb722
Revises: afebc2634ed4
Create Date: 2025-02-05 12:38:16.687243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e239ddb722'
down_revision: Union[str, None] = 'afebc2634ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ClubPreferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ClubPreferences',
    sa.Column('pref_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preferences', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['preferences'], ['TeamIndex.team_index_id'], name='ClubPreferences_preferences_fkey'),
    sa.ForeignKeyConstraint(['users_id'], ['Users.user_id'], name='ClubPreferences_users_id_fkey'),
    sa.PrimaryKeyConstraint('pref_id', name='ClubPreferences_pkey')
    )
    # ### end Alembic commands ###
