"""change naming

Revision ID: 47f635e8f66a
Revises: a808a1ce833e
Create Date: 2025-02-14 01:17:28.889590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f635e8f66a'
down_revision: Union[str, None] = 'a808a1ce833e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InteractionsWithNews', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('InteractionsWithNews_users_id_fkey', 'InteractionsWithNews', type_='foreignkey')
    op.create_foreign_key(None, 'InteractionsWithNews', 'Users', ['user_id'], ['user_id'])
    op.drop_column('InteractionsWithNews', 'users_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InteractionsWithNews', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'InteractionsWithNews', type_='foreignkey')
    op.create_foreign_key('InteractionsWithNews_users_id_fkey', 'InteractionsWithNews', 'Users', ['users_id'], ['user_id'])
    op.drop_column('InteractionsWithNews', 'user_id')
    # ### end Alembic commands ###
