"""fixed_migration

Revision ID: 58c28aef9014
Revises: d64bb5d9a9e5
Create Date: 2025-01-21 22:08:52.268810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c28aef9014'
down_revision: Union[str, None] = 'd64bb5d9a9e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Statuses',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_table('Streams_Status',
    sa.Column('streams_status_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['Statuses.status_id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['Streams.stream_id'], ),
    sa.PrimaryKeyConstraint('streams_status_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Streams_Status')
    op.drop_table('Statuses')
    # ### end Alembic commands ###
