"""new_column_for_news_name

Revision ID: 5a2d68a00873
Revises: df7bd7ffe913
Create Date: 2025-03-10 22:35:56.517828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a2d68a00873'
down_revision: Union[str, None] = 'df7bd7ffe913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TempSubscribersData', sa.Column('news_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TempSubscribersData', 'news_name')
    # ### end Alembic commands ###
