"""change type_of_interaction to interaction_type

Revision ID: 6df39f9ca8f9
Revises: 5a2d68a00873
Create Date: 2025-03-12 15:45:40.176657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df39f9ca8f9'
down_revision: Union[str, None] = '5a2d68a00873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InteractionsWithNews', sa.Column('interaction_type', sa.Integer(), nullable=True))
    op.drop_constraint('InteractionsWithNews_type_of_interaction_fkey', 'InteractionsWithNews', type_='foreignkey')
    op.create_foreign_key(None, 'InteractionsWithNews', 'InteractionTypes', ['interaction_type'], ['interaction_type_id'])
    op.drop_column('InteractionsWithNews', 'type_of_interaction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InteractionsWithNews', sa.Column('type_of_interaction', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'InteractionsWithNews', type_='foreignkey')
    op.create_foreign_key('InteractionsWithNews_type_of_interaction_fkey', 'InteractionsWithNews', 'InteractionTypes', ['type_of_interaction'], ['interaction_type_id'])
    op.drop_column('InteractionsWithNews', 'interaction_type')
    # ### end Alembic commands ###
