"""new_game_statuses_table

Revision ID: 6fd617981728
Revises: 9a5daa74ec72
Create Date: 2025-03-08 14:28:47.823003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd617981728'
down_revision: Union[str, None] = '9a5daa74ec72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Games')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Games',
    sa.Column('game_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sport_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team_away_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team_home_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score_away_team', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score_home_team', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('api_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['Country.country_id'], name='Games_country_id_fkey'),
    sa.ForeignKeyConstraint(['league_id'], ['League.league_id'], name='Games_league_id_fkey'),
    sa.ForeignKeyConstraint(['sport_id'], ['Sports.sport_id'], name='Games_sport_id_fkey'),
    sa.ForeignKeyConstraint(['team_away_id'], ['TeamIndex.team_index_id'], name='Games_team_away_id_fkey'),
    sa.ForeignKeyConstraint(['team_home_id'], ['TeamIndex.team_index_id'], name='Games_team_home_id_fkey'),
    sa.PrimaryKeyConstraint('game_id', name='Games_pkey')
    )
    # ### end Alembic commands ###
