"""api_id_added_to_player_table

Revision ID: 75c86cc206ae
Revises: 873534d472d0
Create Date: 2025-02-23 17:39:03.209503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c86cc206ae'
down_revision: Union[str, None] = '873534d472d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Players', sa.Column('api_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Players', 'api_id')
    # ### end Alembic commands ###
