"""new tables for db

Revision ID: 7cd1eac54db6
Revises: 0bb89241787f
Create Date: 2025-01-04 11:10:18.936176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd1eac54db6'
down_revision: Union[str, None] = '0bb89241787f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('Likes',
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['News.news_id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    op.create_table('Views',
    sa.Column('views_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['News.news_id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('views_id')
    )
    op.create_table('Players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('team_index_id', sa.Integer(), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['Sports.sport_id'], ),
    sa.ForeignKeyConstraint(['team_index_id'], ['TeamIndex.team_index_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('TeamInNews',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('team_index_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['News.news_id'], ),
    sa.ForeignKeyConstraint(['team_index_id'], ['TeamIndex.team_index_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.drop_table('Interactions')
    op.drop_column('BlobIndex', 'test')
    op.drop_constraint('Country_sport_id_fkey', 'Country', type_='foreignkey')
    op.drop_column('Country', 'sport_id')
    op.drop_constraint('TeamIndex_news_id_fkey', 'TeamIndex', type_='foreignkey')
    op.drop_constraint('TeamIndex_country_fkey', 'TeamIndex', type_='foreignkey')
    op.drop_column('TeamIndex', 'country')
    op.drop_column('TeamIndex', 'news_id')
    op.drop_column('Users', 'sport_pref_key')
    op.drop_column('Users', 'club_pref_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('club_pref_key', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('sport_pref_key', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('TeamIndex', sa.Column('news_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('TeamIndex', sa.Column('country', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('TeamIndex_country_fkey', 'TeamIndex', 'Country', ['country'], ['country_id'])
    op.create_foreign_key('TeamIndex_news_id_fkey', 'TeamIndex', 'News', ['news_id'], ['news_id'])
    op.add_column('Country', sa.Column('sport_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Country_sport_id_fkey', 'Country', 'Sports', ['sport_id'], ['sport_id'])
    op.add_column('BlobIndex', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('Interactions',
    sa.Column('interaction_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('news_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interaction_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['News.news_id'], name='Interactions_news_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='Interactions_user_id_fkey'),
    sa.PrimaryKeyConstraint('interaction_id', name='Interactions_pkey')
    )
    op.drop_table('TeamInNews')
    op.drop_table('Players')
    op.drop_table('Views')
    op.drop_table('Likes')
    op.drop_table('Category')
    # ### end Alembic commands ###
