"""new_table_for_url

Revision ID: 9a5daa74ec72
Revises: 8d79017f4a3e
Create Date: 2025-03-08 13:50:43.223199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5daa74ec72'
down_revision: Union[str, None] = '8d79017f4a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StreamUrl',
    sa.Column('stream_url_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('stream_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['Streams.stream_id'], ),
    sa.PrimaryKeyConstraint('stream_url_id')
    )
    op.drop_column('Streams', 'stream_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Streams', sa.Column('stream_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('StreamUrl')
    # ### end Alembic commands ###
