"""Added table with temporiar info

Revision ID: 9ee0c3368f94
Revises: 791b5a36000c
Create Date: 2025-02-20 20:56:45.346390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee0c3368f94'
down_revision: Union[str, None] = '791b5a36000c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TempSubscribersData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_ids', sa.Integer(), nullable=True),
    sa.Column('subscriber_emails', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_ids'], ['TeamIndex.team_index_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TempSubscribersData')
    # ### end Alembic commands ###
