"""+save_at in News; -theme in Users; +Interactions

Revision ID: a206ce4b35b7
Revises: c07f730a359d
Create Date: 2024-11-12 22:26:25.612464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a206ce4b35b7'
down_revision: Union[str, None] = 'c07f730a359d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Interactions',
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('interaction_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['News.news_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('interaction_id')
    )
    op.add_column('News', sa.Column('save_at', sa.DateTime(), nullable=True))
    op.drop_column('Users', 'theme')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('theme', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('News', 'save_at')
    op.drop_table('Interactions')
    # ### end Alembic commands ###
