"""changed tables for interactions

Revision ID: a808a1ce833e
Revises: 410e5fdf3a6e
Create Date: 2025-02-13 21:56:02.929959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a808a1ce833e'
down_revision: Union[str, None] = '410e5fdf3a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('InteractionTypes',
    sa.Column('interaction_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('interaction_type_id')
    )
    op.create_table('InteractionsWithNews',
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('type_of_interaction', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['News.news_id'], ),
    sa.ForeignKeyConstraint(['type_of_interaction'], ['InteractionTypes.interaction_type_id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('interaction_id')
    )
    op.drop_table('Views')
    op.drop_table('Likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Likes',
    sa.Column('like_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['News.news_id'], name='Likes_news_id_fkey'),
    sa.ForeignKeyConstraint(['users_id'], ['Users.user_id'], name='Likes_users_id_fkey'),
    sa.PrimaryKeyConstraint('like_id', name='Likes_pkey')
    )
    op.create_table('Views',
    sa.Column('views_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['News.news_id'], name='Views_news_id_fkey'),
    sa.ForeignKeyConstraint(['users_id'], ['Users.user_id'], name='Views_users_id_fkey'),
    sa.PrimaryKeyConstraint('views_id', name='Views_pkey')
    )
    op.drop_table('InteractionsWithNews')
    op.drop_table('InteractionTypes')
    # ### end Alembic commands ###
