"""new blin ClubPreferences table

Revision ID: afebc2634ed4
Revises: 27eb623b7b34
Create Date: 2025-02-05 12:36:19.514925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afebc2634ed4'
down_revision: Union[str, None] = '27eb623b7b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserClubPreferences',
    sa.Column('pref_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('preferences', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['preferences'], ['TeamIndex.team_index_id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('pref_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserClubPreferences')
    # ### end Alembic commands ###
