"""Updated database structure

Revision ID: c444f031961a
Revises: a206ce4b35b7
Create Date: 2024-11-17 14:25:14.741976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c444f031961a'
down_revision: Union[str, None] = 'a206ce4b35b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('News', sa.Column('sport_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'News', 'Sports', ['sport_id'], ['sport_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'News', type_='foreignkey')
    op.drop_column('News', 'sport_id')
    # ### end Alembic commands ###
