"""Token col

Revision ID: d21e5db4136c
Revises: 0d93e8ea82b6
Create Date: 2025-03-20 19:43:34.791298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21e5db4136c'
down_revision: Union[str, None] = '0d93e8ea82b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('News', 'interest_rate')
    op.add_column('Token_blocklist', sa.Column('token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token_blocklist', 'token')
    op.add_column('News', sa.Column('interest_rate', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
