"""Added sport_img

Revision ID: e56018466c09
Revises: 7970439d3a08
Create Date: 2024-12-04 14:19:31.852637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56018466c09'
down_revision: Union[str, None] = '7970439d3a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sports', sa.Column('sport_img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sports', 'sport_img')
    # ### end Alembic commands ###
